name: Build and Deploy MkDocs

on:
  # Run on pushes to main (i.e. when we merge a PR)
  push:
    branches: [main]
    # Only run if the docs files have changed
    paths:
      - mkdocs.yml
      - docs/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python_version: '3.13'
        cache: pip
      
    - name: Install MkDocs and dependencies
      run: python3 -m pip install mkdocs mkdocs-material mkdocs-render-swagger-plugin

    # Build into _site dir
    - name: Build MkDocs
      run: python3 -m mkdocs build --site-dir=_site

    # Temp measure: output to an artifact, so that it can be downloaded if needed
    - name: Upload built artifact
      uses: actions/upload-artifact@v4
      with:
        name: mkdocs-dir
        path: _site/
        retention-days: 5

    # Upload to server directory
    - name: Deploy to sites@grinnell
      uses: burnett01/rsync-deployments@7.0.2
      with:
        # -v       : Verbose, print all transfers
        # -z       : Compress files during transfer to save on bandwidth
        # -r       : Recurse into directories
        # --delete : Delete files that are at the destination but not the source
        switches: -vzr --delete

        # the trailing slash on `path` ensures we copy the contents, not the dir itself.
        # so we end up with `.../docs/index.html` not `.../docs/_site/index.html`
        path: _site/
        remote_path: /home/heilalmond/getgrinnected.sites.grinnell.edu/docs

        # ssh connection details
        remote_host: ${{ vars.SITES_SSH_HOSTNAME }}
        remote_port: ${{ vars.SITES_SSH_PORT }}
        remote_user: ${{ vars.SITES_SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVKEY }}
