name: Kotlin CI

# run on pull requests targeting main
on:
  push:
    branches: [ 'Kotlin-workflow' ] # TODO: DELETE TEMP
  pull_request:
    branches: [ $default-branch ]
    paths:
      - src/android/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # https://github.com/marketplace/actions/android-emulator-runner
    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    # https://github.com/marketplace/actions/android-emulator-runner
    - name: Run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        working-directory: ./src/android/GetGrinnected/MyApplication
        api-level: 28 # https://github.com/SORMAS-Foundation/SORMAS-Project/blob/development/.github/workflows/sormas_app_ci.yml#L32
        script: ./gradlew connectedAndroidTest
