name: Build MkDocs

on:
  # Run on pushes to specified branches.
  # TODO: Temp value of `create-docs` to test, but should become only $default-branch before switching to main
  push:
    branches: [ $default-branch, create-docs ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build with MkDocs
      uses: romw314/mkdocs-action@v9

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: docs/_site/
        if-no-files-found: error

  # TODO: deploy step that deploys to the actual website
