name: Build and Deploy MkDocs

on:
  # Run on pushes to specified branches.
  # TODO: Temp value of `create-docs` to test, but should become only $default-branch before switching to main
  push:
    branches: [ $default-branch, create-docs ]
    paths:
      - docs/**
      - mkdocs.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Build into _site dir
    - name: Build with MkDocs
      uses: romw314/mkdocs-action@v9

    # TODO: UPLOAD ARTIFACT HERE IF NEEDED, BUT MAY NOT BE NEEDED

    # Upload to server directory
    - name: Deploy
      uses: burnett01/rsync-deployments@7.0.2
      with:
        # -v       : Verbose, print all transfers
        # -z       : Compress files during transfer to save on bandwidth
        # -r       : Recurse into directories
        # --delete : Delete files that are at the destination but not the source
        switches: -vzr --delete
        path: _site
        remote_path: /home/heilalmond/getgrinnected.sites.grinnell.edu/docs
        remote_host: ${{ vars.SITES_SSH_HOSTNAME }}
        remote_port: ${{ vars.SITES_SSH_PORT }}
        remote_user: ${{ vars.SITES_SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVKEY }}
